[general]
version = "1.0.0"
last_cvm_version = "0.0.1"

[init]
git_assets = "https://github.com/orelvis15/cvm/releases/download"
config_path = "https://raw.githubusercontent.com/orelvis15/cvm_config/master/"
ghcup_path = "https://get-ghcup.haskell.org"
libsodium_repository = "https://github.com/input-output-hk/libsodium.git"
libsodium_commit = "66f017f1"
install_ghc_file = "install_ghc"
haskell_ghc_version = "8.10.7"
haskell_cabal_version = "3.6.2.0"

[workspace]
workspace_folder = "cardano"

[dependencies]
macos = ["coreutils", "gnupg", "jq", "libsodium", "tcptraceroute"]
debian = ["libpq-dev", "python3", "build-essential", "pkg-config", "libffi-dev", "libgmp-dev", "libssl-dev", "libtinfo-dev", "systemd", "libsystemd-dev", "libsodium-dev", "zlib1g-dev", "make", "g++", "tmux", "git", "jq", "libncursesw5", "gnupg", "aptitude", "libtool", "autoconf", "secure-delete", "iproute2", "bc", "tcptraceroute", "dialog", "automake", "sqlite3", "bsdmainutils", "libusb-1.0-0-dev", "libudev-dev", "curl"]
ubuntu = ["libpq-dev", "python3", "build-essential", "pkg-config", "libffi-dev", "libgmp-dev", "libssl-dev", "libtinfo-dev", "systemd", "libsystemd-dev", "libsodium-dev", "zlib1g-dev", "make", "g++", "tmux", "git", "jq", "libncursesw5", "gnupg", "aptitude", "libtool", "autoconf", "secure-delete", "iproute2", "bc", "tcptraceroute", "dialog", "automake", "sqlite3", "bsdmainutils", "libusb-1.0-0-dev", "libudev-dev", "curl", "unzip"]
centos = ["python3", "coreutils", "libffi-devel", "gmp-devel", "openssl-devel", "ncurses-libs", "systemd", "systemd-devel", "libsodium-devel", "zlib-devel", "make", "gcc-c++", "tmux", "git", "jq", "gnupg2", "libtool", "autoconf", "iproute", "bc", "traceroute", "dialog", "sqlite", "util-linux", "xz", "curl"]
centos_7 = ["libusb", "pkconfig", "srm"]
centos_8 = ["libusbx", "ncurses-compat-libs", "pkgconf-pkg-config"]
rhel = ["python3", "coreutils", "libffi-devel", "gmp-devel", "openssl-devel", "ncurses-libs", "systemd", "systemd-devel", "libsodium-devel", "zlib-devel", "make", "gcc-c++", "tmux", "git", "jq", "gnupg2", "libtool", "autoconf", "iproute", "bc", "traceroute", "dialog", "sqlite", "util-linux", "xz", "curl"]
rhel_7 = ["libusb", "pkconfig", "srm"]
rhel_8 = ["libusbx", "ncurses-compat-libs", "pkgconf-pkg-config"]
fedora = ["python3", "coreutils", "libffi-devel", "gmp-devel", "openssl-devel", "ncurses-libs", "systemd", "systemd-devel", "libsodium-devel", "zlib-devel", "make", "gcc-c++", "tmux", "git", "jq", "gnupg2", "libtool", "autoconf", "iproute", "bc", "traceroute", "dialog", "sqlite", "util-linux", "xz", "libusbx", "ncurses-compat-libs", "pkgconf-pkg-config", "srm", "curl"]

[build_cardano_node]
cnode_repository = "https://github.com/input-output-hk/cardano-node.git"
cnode_release = "https://api.github.com/repos/input-output-hk/cardano-node/releases/latest"

# Folder Structure

[[structure_folder_item]]
key = "SCRIPT"
name = "script"

[[structure_folder_item]]
key = "FILES"
name = "files"

[[structure_folder_item]]
key = "DB"
name = "db"

[[structure_folder_item]]
key = "GUILDDB"
name = "guild-db"

[[structure_folder_item]]
key = "SOCKETS"
name = "sockets"

[[structure_folder_item]]
key = "PRIV"
name = "priv"

[[structure_folder_item]]
key = "TMP"
name = "tmp"

[[structure_folder_item]]
key = "LOGS"
name = "logs"

[[structure_folder_item]]
key = "BIN"
name = "bin"

[[structure_folder_item]]
key = "GIT"
name = "git"

# Config files

[[config_file_item]]
url = "https://hydra.iohk.io/job/Cardano/iohk-nix/cardano-deployment/latest-finished/download/1/{network}-byron-genesis.json"
name = "byron-genesis.json"
folder = "files"

[[config_file_item]]
url = "https://hydra.iohk.io/job/Cardano/iohk-nix/cardano-deployment/latest-finished/download/1/{network}-shelley-genesis.json"
name = "shelley-genesis.json"
folder = "files"

[[config_file_item]]
url = "https://hydra.iohk.io/job/Cardano/iohk-nix/cardano-deployment/latest-finished/download/1/{network}-alonzo-genesis.json"
name = "alonzo-genesis.json"
folder = "files"

[[config_file_item]]
url = "https://hydra.iohk.io/job/Cardano/iohk-nix/cardano-deployment/latest-finished/download/1/{network}-topology.json"
name = "topology.json"
folder = "files"

[[config_file_item]]
url = "https://raw.githubusercontent.com/cardano-community/guild-operators/master/files/config-{network}.json"
name = "config.json"
folder = "files"

[[config_file_item]]
url = "https://raw.githubusercontent.com/cardano-community/guild-operators/master/files/config-dbsync.json"
name = "config-dbsync.json"
folder = "files"

# Script helpers

[[config_file_item]]
url = "https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/env"
name = "env"
folder = "script"

[[config_file_item]]
url = "https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/cnode.sh"
name = "cnode.sh"
folder = "script"

[[config_file_item]]
url = "https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/dbsync.sh"
name = "dbsync.sh"
folder = "script"

[[config_file_item]]
url = "https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/cntools.sh"
name = "cntools.sh"
folder = "script"

[[config_file_item]]
url = "https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/cntools.library"
name = "cntools.library"
folder = "script"

[[config_file_item]]
url = "https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/logMonitor.sh"
name = "logMonitor.sh"
folder = "script"

[[config_file_item]]
url = "https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/setup_mon.sh"
name = "setup_mon.sh"
folder = "script"

[[config_file_item]]
url = "https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/topologyUpdater.sh"
name = "topologyUpdater.sh"
folder = "script"

[[config_file_item]]
url = "https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/cabal-build-all.sh"
name = "cabal-build-all.sh"
folder = "script"

[[config_file_item]]
url = "https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/submitapi.sh"
name = "submitapi.sh"
folder = "script"

[[config_file_item]]
url = "https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/ogmios.sh"
name = "ogmios.sh"
folder = "script"

[[config_file_item]]
url = "https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/system-info.sh"
name = "system-info.sh"
folder = "script"

[[config_file_item]]
url = "https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/sLiveView.sh"
name = "sLiveView.sh"
folder = "script"

[[config_file_item]]
url = "https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/gLiveView.sh"
name = "gLiveView.sh"
folder = "script"

[[config_file_item]]
url = "https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/deploy-as-systemd.sh"
name = "deploy-as-systemd.sh"
folder = "script"

[[config_file_item]]
url = "https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/cncli.sh"
name = "cncli.sh"
folder = "script"

[[config_file_item]]
url = "https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/grest-helper-scripts/setup-grest.sh"
name = "setup-grest.sh"
folder = "script"